version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: express-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/userpicture
      - backend_data:/app/userPictureBeforeResizing
    environment:
      - NODE_ENV=production
      - TOKEN=justForTest
      - DB_URL=mongodb+srv://dhiamlayah:0000@cluster0.0s4sv.mongodb.net/
      - PORT=8000 
    env_file: 
      - ./server/.env    
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_port=${REACT_APP_port} 
    env_file: 
      - ./client/.env  
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
