# Stage 1: Build the backend
FROM node:18-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Compile TypeScript files (if your project uses TypeScript)
RUN npx tsc

# Stage 2: Production Image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist /app/dist
COPY --from=build /app/userPicture /app/dist/userPicture
COPY --from=build /app/userPictureBeforResizing /app/dist/userPictureBeforResizing

# Install production dependencies
RUN npm install --production

# Expose the port your app runs on (replace 3000 with your actual port if different)
EXPOSE 8000

# Start the application
CMD ["node", "dist/server.js"]
